# Plugin Configuration for iCore (by MineGlade)

# =====================================================
#                       Prefixes
# =====================================================
# you can use color codes with an & character.
# &a-f,0-1,k,l,m,n,o

command-prefix: "&8[&bP&8] &7| "
chat-prefix: "&8[&6C&8] &7| "
join-prefix: "&f[&a+&f] &7| "
leave-prefix: "&f[&c-&f] &7| "

# =====================================================
#                        MySQL
# =====================================================

mysql:
  host: "localhost"
  port: 3306
  database: "db"
  user: "root"
  password: "password"

# =====================================================
#                  Message Of The Day
# =====================================================
# you can use PlaceholderAPI PlaceHolders

motd:
  - text: "\n&8[&bP&8] &7| Hey there, "
  - text: "&a%player_displayname%"
    hover: "&7That's your name, right?"
  - text: "&7!\n&8[&bP&8] &7| There are currently &a%server_online%&7 players online."
    suggest_command: "/list"
  - text: "\n&8[&bP&8] &7| &f&nClick here to join the discord.\n"
    url: "https://d.minegla.de/"

# =====================================================
#                         Voting
# =====================================================
# you can use PlaceholderAPI PlaceHolders
vote-response:
  - text: "\n&8[&bP&8] &7| ======= &aVoting Sites&7 ======="
  
  - text: "\n&8[&bP&8] &7| The server owner has forgotten to add their own vote-sites list,\n&8[&bP&8] &7| so here is a list of sites to vote on for &fMine&aGlade\n"
    
  - text: "\n&8[&bP&8] &7| &71. &aminecraft-server-list"
    hover: "vote for us on minecraft-server-list.com!"
    url: "https://minecraft-server-list.com/server/416687/vote/"
  
  - text: "\n&8[&bP&8] &7| &72. &aminecraft-mp"
    hover: "vote for us on minecraft-mp.com!"
    url: "https://minecraft-mp.com/server/222832/vote/"
  
  - text: "\n&8[&bP&8] &7| &73. &aminecraftservers"
    hover: "vote for us on minecraftservers.org!"
    url: "https://minecraftservers.org/vote/439188"
    
  - text: "\n&8[&bP&8] &7| &74. &atopg"
    hover: "vote for us on topg.org!"
    url: "https://topg.org/Minecraft/in-513647"
  
  - text: "\n&8[&bP&8] &7| &75. &amccommunity"
    hover: "vote for us on mccommunity.net!"
    url: "https://mccommunity.net/server/106-MineGlade/vote/"
  - text: "\n"
  
  - text: "\n&8[&bP&8] &7| You currently have &a%votes% &7votes."

# =====================================================
#                     Discord Bot
# =====================================================
# KEEP YOUR BOT TOKEN PRIVATE AT ALL TIMES!
# THIS TOKEN ALLOWS FULL ACCESS TO YOUR BOT USER!

discord-bot:
  token: "your-token" 

# =====================================================