main: com.mineglade.icore.ICore
name: iCore
description: "A plugin to run the core of your game server; Chat Formatting, Vote Listener, Discord Chat Relay, Nicknames"
version: 0.02-alpha
authors: [patchtv, Derkades]
website: https://www.github.com/mineglade/icore
api-version: 1.13
depend: [Vault, PlaceholderAPI]
softdepend: [SuperVanish, Votifier]

commands:
# Basic commands:
  icore:
    description: "core command for iCore"
    usage: "/icore help"
    aliases: [ic]
  ping:
    description: "returns the player's ping to the server."
    usage: "/ping"
    aliases: [hi, pong, pung, peng, pang]
    
# Vote commands:
  vote:
    description: "returns a list of sites to vote on."
    usage: "/vote"
    
# Emote Commands
  bear:
    description: "sends a ʕ•ᴥ•ʔ with a provided message"
    usage: "/bear [message]"
  flower:
    description: "sends a (◕‿◕✿) with a provided message"
    usage: "/bear [message]"
  gib:
    description: "sends a ༼ つ ◕_◕ ༽つ with a provided message"
    usage: "/gib [message]"
  lenny:
    description: "sends a ( ͡° ͜ʖ ͡°) with a provided message"
    usage: "/lenny [message]"
  love:
    description: "sends a (づ￣ ³￣)づ with a provided message"
    usage: "/love [message]"
  mao:
    description: "sends a ฅ^•ﻌ•^ฅ with a provided message"
    usage: "/mao [message]"
  shrug:
    description: "sends a ¯\\_(ツ)_/¯ with a provided message"
    usage: "/shrug [message]"
  tableflip:
    description: "sends a (╯°□°）╯︵ ┻━┻ with a provided message"
    usage: "/tableflip [message]"
  unflip:
    description: "sends a ┬─┬ ノ( ゜-゜ノ) with a provided message"
    usage: "/unflip [message]"
  yes:
    description: "sends a •ᴗ• with a provided message"
    usage: "/yes [message]"

  suggest:
    description: "suggest a feature to the dedicated GitHub repository"
    usage: "/suggest"

permissions:

# Command permissions:
  
  # Basic commands:
  icore.command.help:
    description: "allows the player to use /icore"
    default: true
  icore.command.ping:
    description: "allows the player to use /ping"
    default: true
    
  # Vote commands:
  icore.command.vote: 
    description: "allows the player to use /vote"
    default: true
  icore.command.vote.top:
    description: "allows the player to use /vote top"
    default: true
  
  # Support commands:
  icore.command.support:
    description: "allows the player to use /support"
    default: true
  icore.command.support.receive:
    description: "allows the player to receive support queries, and use /support inbox"
    default: op
    
  # Misc commands
  icore.command.color.chat:
    description: "allows the user to set their chat color"
    default: true
  icore.command.color.chat.format:
    description: "allows the user to set their chat formatting"
    default: true
  icore.command.color.chat.other:
    description: "allows the user to set another player's chat color"
    default: op
    
  icore.command.color.name:
    description: "allows the user to set their name color"
    default: true
  icore.command.color.name.format:
    description: "allows the user to set their name formatting"
    default: true
  icore.command.color.name.other:
    description: "allows the user to set another player's name color"
    default: op


  # Emote commands:
  icore.command.emotes.bear:
    description: "allows the user to use /bear"
    default: true
  icore.command.emotes.flower:
    description: "allows the user to use /flower"
    default: true
  icore.command.emotes.gib:
    description: "allows the user to use /gib"
    default: true
  icore.command.emotes.lenny:
    description: "allows the user to use /lenny"
    default: true
  icore.command.emotes.love:
    description: "allows the user to use /love"
    default: true
  icore.command.emotes.mao:
    description: "allows the user to use /mao"
    default: true
  icore.command.emotes.shrug:
    description: "allows the user to use /shrug"
    default: true
  icore.command.emotes.tableflip:
    description: "allows the user to use /tableflip"
    default: true
  icore.command.emotes.unflip:
    description: "allows the user to use /unflip"
    default: true
  icore.command.emotes.yes:
    description: "allows the user to use /yes"
    default: true
  
  
  
  # Admin commands:
  icore.command.reload:
    description:  "allows the user to use /ic reload"
    default: op

# Color & format permissions:
  icore.color.chat.reset:
    description: "allows the user to set their chat formatting to bold"
    default: true

  icore.color.chat.aqua:
    description: "allows the user to set their chat color to aqua"
    default: op
  icore.color.chat.black:
    description: "allows the user to set their chat color to black"
    default: op
  icore.color.chat.blue:
    description: "allows the user to set their chat color to blue"
    default: op
  icore.color.chat.dark_aqua:
    description: "allows the user to set their chat color to dark aqua"
    default: op
  icore.color.chat.dark_blue:
    description: "allows the user to set their chat color to dark blue"
    default: op
  icore.color.chat.dark_green:
    description: "allows the user to set their chat color to dark green"
    default: op
  icore.color.chat.dark_gray:
    description: "allows the user to set their chat color to dark gray"
    default: op
  icore.color.chat.dark_purple:
    description: "allows the user to set their chat color to dark purple"
    default: op
  icore.color.chat.dark_red:
    description: "allows the user to set their chat color to dark red"
    default: op
  icore.color.chat.gold:
    description: "allows the user to set their chat color to gold"
    default: op
  icore.color.chat.gray:
    description: "allows the user to set their chat color to aqua"
    default: op
  icore.color.chat.green:
    description: "allows the user to set their chat color to green"
    default: op
  icore.color.chat.light_purple:
    description: "allows the user to set their chat color to light purple"
    default: op
  icore.color.chat.red:
    description: "allows the user to set their chat color to red"
    default: op
  icore.color.chat.white:
    description: "allows the user to set their chat color to white"
    default: op
  icore.color.chat.yellow:
    description: "allows the user to set their chat color to yellow"
    default: op
  
  icore.color.chat.bold:
    description: "allows the user to set their chat formatting to bold"
    default: op
  icore.color.chat.italic:
    description: "allows the user to set their chat formatting to italic"
    default: op
  icore.color.chat.magic:
    description: "allows the user to set their chat formatting to magic"
    default: op
  icore.color.chat.strikethrough:
    description: "allows the user to set their chat formatting to strikethrough"
    default: op
  icore.color.chat.underline:
    description: "allows the user to set their chat formatting to underline"
    default: op
  
  icore.color.name.reset:
    description: "allows the user to set their chat formatting to bold"
    default: true

  icore.color.name.aqua:
    description: "allows the user to set their chat color to aqua"
    default: op
  icore.color.name.black:
    description: "allows the user to set their chat color to black"
    default: op
  icore.color.name.blue:
    description: "allows the user to set their chat color to blue"
    default: op
  icore.color.name.dark_aqua:
    description: "allows the user to set their chat color to dark aqua"
    default: op
  icore.color.name.dark_blue:
    description: "allows the user to set their chat color to dark blue"
    default: op
  icore.color.name.dark_green:
    description: "allows the user to set their chat color to dark green"
    default: op
  icore.color.name.dark_gray:
    description: "allows the user to set their chat color to dark gray"
    default: op
  icore.color.name.dark_purple:
    description: "allows the user to set their chat color to dark purple"
    default: op
  icore.color.name.dark_red:
    description: "allows the user to set their chat color to dark red"
    default: op
  icore.color.name.gold:
    description: "allows the user to set their chat color to gold"
    default: op
  icore.color.name.gray:
    description: "allows the user to set their chat color to aqua"
    default: op
  icore.color.name.green:
    description: "allows the user to set their chat color to green"
    default: op
  icore.color.name.light_purple:
    description: "allows the user to set their chat color to light purple"
    default: op
  icore.color.name.red:
    description: "allows the user to set their chat color to red"
    default: op
  icore.color.name.white:
    description: "allows the user to set their chat color to white"
    default: op
  icore.color.name.yellow:
    description: "allows the user to set their chat color to yellow"
    default: op

  icore.color.name.bold:
    description: "allows the user to set their chat formatting to bold"
    default: op
  icore.color.name.italic:
    description: "allows the user to set their chat formatting to italic"
    default: op
  icore.color.name.magic:
    description: "allows the user to set their chat formatting to magic"
    default: op
  icore.color.name.strikethrough:
    description: "allows the user to set their chat formatting to strikethrough"
    default: op
  icore.color.name.underline:
    description: "allows the user to set their chat formatting to underline"
    default: op

# Chat permissions:
  icore.chat.use_colors:
    description: "allows the user to use color-codes in chat."
    default: op
  

      

  