main: com.mineglade.icore.ICore
name: iCore
description: "A plugin to run the core of your game server; Chat Formatting, Vote Listener, Discord Chat Relay, Nicknames"
version: 0.02-alpha
authors: [patchtv, Derkades]
website: https://www.github.com/mineglade/icore
depend: [Vault, PlaceholderAPI]
softdepend: [SuperVanish, Votifier]

commands:

  icore:
    description: "core command for iCore"
    usage: "/icore help"
    aliases: [ic]
    permission: icore.help

  vote:
    description: "returns a list of sites to vote on."
    usage: "/vote"
    permission: icore.vote

  ping:
    description: "returns the player's ping to the server."
    usage: "/ping"
    aliases: [hi, pong, pung, peng, pang]

  shrug:
    description: "sends a ¯\\(ツ)/¯ with a provided message."
    usage: "/shrug"

  suggest:
    description: "suggest a feature to the dedicated GitHub repository"
    usage: "/suggest"

permissions:

# Default Permissions:
  icore.help:
    description: "allows the player to use /icore"
    default: true

# Vote Permissions:
  icore.vote:
    description: "allows the player to use /vote"
    default: true
  icore.vote.top:
    description: "allows the player to use /vote top"
    default: true

# Chat Permissions:
  icore.chat.color:
    description: "allows color in chat."
    default: op
    
# Misc Permissions:
  icore.ping:
    description: "allows the player to use /ping"
    default: true
  icore.shrug:
    description: "allows the player to use /shrug"
    default: true

# Support permissions:
  icore.support:
    description: "allows the player to use /support"
    default: true
  icore.support.receive:
    description: "allows the player to receive support queries, and use /support inbox"
    default: op

# Administrator permissions:
  icore.reload:
    description: "allows the player to use /ic reload"
    default: op


# WildCards:
  icore.misc:
    description: "allows all misc commands"
    default: true
    children:
      icore.shrug: true
      icore.ping: true

  icore.admin:
    description: "allows all admin commands"
    default: op
    children:
      icore.reload: true

  icore.vote.*:
    description: "wildcard permission for all icore.vote permissions"
    default: true
    children:
      icore.vote: true
      icore.vote.top: true

  icore.support.*:
    description: "wildcard permission for all icore.support permissions"
    default: op
    children:
      icore.support: true
      icore.support.receive: true

  icore.*:
    description: "wildcard permission to allow all icore commands."
    default: op
    children:
      icore.help: true
      icore.chat.color: true
      icore.misc: true
      icore.admin: true
      icore.vote.*: true
      icore.support.*: true
      

  