# =====================================================
#                         Chat
# =====================================================
# Depending on your enabled modules, you may use Moda Placeholders.
# PAPI Placeholders will work if installed.
#
# Placeholders that will work without any other modules 
# or plugins are listed on https://github.com/mineglade/moda/wiki/Placeholders
#
# More examples and placeholders can be found on this wiki page:
# https://github.com/mineglade/moda/wiki/Chat

# =====================================================
#                       Formatting
# =====================================================
# In this section you may define the format you wish for 
# your chat messages to uphold.
# 
# A simple chat format would be:
format:
  - text: "{PLAYER} » {MESSAGE}"
  
# The following example includes more advanced chat 
# formatting options (think hovers and click events):

#format:
#  # a chat prefix
#  - text: "&8[&6C&8] &7| "
#  
#  # a player component
#  - text: "{PREFIX}&r {DSIPLAYNAME}&r {SUFFIX}"
#    hover: |
#      username: {PLAYER}
#      group: {GROUP}
#    suggest_command: "/tell {PLAYER}"
#  
#  # the chat message
#  - text: "» {MESSAGE}"

# =====================================================
#                   Message of the Day
# =====================================================
# In this section you may define the MOTD the player  
# will receive upon joining the server.
# MAKE SURE YOU INCLUDE \n (line breaks) WHERE YOU WANT THEM!

# A simple MOTD would be:
motd:
  - text: "&7Hey there, &a{PLAYER}&7!"
  - text: "\n&7Welcome to the server!"
  - text: "\n&7There are &a{ONLINE}&7/{MAX} players online."

# The following example includes more advanced options:
#motd:
#  - text: "\n&8[&bM&8] &7 | Hey there, "
#  - text: "{DISPLAYNAME}"
#    hover: "&7That's your name, right?"
#  - text: "\n&8[&bM&8] &7 | There are currently &a{ONLINE}&7 players online."
#    suggest_command: "/list"
#  - text: "\n&8[&bM&8] &7 | "
#  - text: "&f&nClick here to view the site.\n"
#    url: "https://your-site.com/"
  